-- MySQL Script generated by MySQL Workbench
-- 06/04/15 10:45:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema estacao_fitness
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estacao_fitness
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estacao_fitness` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `estacao_fitness` ;

-- -----------------------------------------------------
-- Table `estacao_fitness`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacao_fitness`.`professor` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `matricula` INT NOT NULL UNIQUE,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `urlFoto` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idProfessor`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacao_fitness`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacao_fitness`.`aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `peso` DOUBLE NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `urlFoto` VARCHAR(45) NULL,
  `matricula` INT NOT NULL UNIQUE,
  PRIMARY KEY (`idAluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacao_fitness`.`Recepcionista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacao_fitness`.`recepcionista` (
  `idRecepcionista` INT NOT NULL AUTO_INCREMENT,
  `matricula` INT NOT NULL UNIQUE,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `urlFoto` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idRecepcionista`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacao_fitness`.`Estagiario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacao_fitness`.`estagiario` (
  `idEstagiario` INT NOT NULL AUTO_INCREMENT,
  `matricula` INT NOT NULL UNIQUE,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `urlFoto` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstagiario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacao_fitness`.`Nutricionista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacao_fitness`.`nutricionista` (
  `idNutricionista` INT NOT NULL AUTO_INCREMENT,
  `matricula` INT NOT NULL UNIQUE,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `urlFoto` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idNutricionista`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacao_fitness`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacao_fitness`.`telefone` (
  `idTelefone` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `idProfessorFK` INT NULL,
  `idAlunoFK` INT NULL,
  `idRecepcionistaFK` INT NULL,
  `idEstagiarioFK` INT NULL,
  `idNutricionistaFK` INT NULL,
  PRIMARY KEY (`idTelefone`),
  INDEX `fk_Telefone_Cliente1_idx` (`idAlunoFK` ASC),
  INDEX `fk_Telefone_Professor_idx` (`idProfessorFK` ASC),
  INDEX `fk_Telefone_Recepcionista1_idx` (`idRecepcionistaFK` ASC),
  INDEX `fk_Telefone_Estagiario1_idx` (`idEstagiarioFK` ASC),
  INDEX `fk_Telefone_Nutricionista1_idx` (`idNutricionistaFK` ASC),
  CONSTRAINT `idProfessorFK`
    FOREIGN KEY (`idProfessorFK`)
    REFERENCES `estacao_fitness`.`Professor` (`idProfessor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idClienteFK`
    FOREIGN KEY (`idAlunoFK`)
    REFERENCES `estacao_fitness`.`Aluno` (`idAluno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Telefone_Recepcionista1`
    FOREIGN KEY (`idRecepcionistaFK`)
    REFERENCES `estacao_fitness`.`Recepcionista` (`idRecepcionista`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefone_Estagiario1`
    FOREIGN KEY (`idEstagiarioFK`)
    REFERENCES `estacao_fitness`.`Estagiario` (`idEstagiario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefone_Nutricionista1`
    FOREIGN KEY (`idNutricionistaFK`)
    REFERENCES `estacao_fitness`.`Nutricionista` (`idNutricionista`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacao_fitness`.`Sugestao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacao_fitness`.`sugestao` (
  `idSugestao` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `descricao` TEXT(300) NOT NULL,
  `areaSugestao` VARCHAR(45) NOT NULL,
  `idAlunoFK` INT NOT NULL,
  PRIMARY KEY (`idSugestao`),
  INDEX `fk_Sugestao_Cliente1_idx` (`idAlunoFK` ASC),
  CONSTRAINT `fk_Sugestao_Cliente1`
    FOREIGN KEY (`idAlunoFK`)
    REFERENCES `estacao_fitness`.`Aluno` (`idAluno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacao_fitness`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacao_fitness`.`avaliacao` (
  `idAvaliacao` INT NOT NULL AUTO_INCREMENT,
  `dataAvaliacao` DATE NOT NULL,
  `resultado` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `validade` DATE NOT NULL,
  `idProfessorFK` INT NOT NULL,
  `idAlunoFK` INT NOT NULL,
  PRIMARY KEY (`idAvaliacao`),
  INDEX `fk_Avaliacao_Professor1_idx` (`idProfessorFK` ASC),
  INDEX `fk_Avaliacao_Cliente1_idx` (`idAlunoFK` ASC),
  CONSTRAINT `fk_Avaliacao_Professor1`
    FOREIGN KEY (`idProfessorFK`)
    REFERENCES `estacao_fitness`.`Professor` (`idProfessor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Avaliacao_Cliente1`
    FOREIGN KEY (`idAlunoFK`)
    REFERENCES `estacao_fitness`.`Aluno` (`idAluno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacao_fitness`.`Exercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacao_fitness`.`exercicio` (
  `idExercicio` INT NOT NULL AUTO_INCREMENT,
  `descricao` TIMESTAMP NOT NULL,
  `idEstagiarioFK` INT NOT NULL,
  `idProfessorFK` INT NOT NULL,
  `idAlunoFK` INT NOT NULL,
  PRIMARY KEY (`idExercicio`),
  INDEX `fk_Exercicio_Estagiario1_idx` (`idEstagiarioFK` ASC),
  INDEX `fk_Exercicio_Professor1_idx` (`idProfessorFK` ASC),
  INDEX `fk_Exercicio_Cliente1_idx` (`idAlunoFK` ASC),
  CONSTRAINT `fk_Exercicio_Estagiario1`
    FOREIGN KEY (`idEstagiarioFK`)
    REFERENCES `estacao_fitness`.`Estagiario` (`idEstagiario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Exercicio_Professor1`
    FOREIGN KEY (`idProfessorFK`)
    REFERENCES `estacao_fitness`.`Professor` (`idProfessor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Exercicio_Cliente1`
    FOREIGN KEY (`idAlunoFK`)
    REFERENCES `estacao_fitness`.`Aluno` (`idAluno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacao_fitness`.`Dieta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacao_fitness`.`dieta` (
  `idDieta` INT NOT NULL AUTO_INCREMENT,
  `validade` DATE NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `idNutricionistaFK` INT NOT NULL,
  `idAlunoFK` INT NOT NULL,
  PRIMARY KEY (`idDieta`),
  INDEX `fk_Dieta_Nutricionista1_idx` (`idNutricionistaFK` ASC),
  INDEX `fk_Dieta_Cliente1_idx` (`idAlunoFK` ASC),
  CONSTRAINT `fk_Dieta_Nutricionista1`
    FOREIGN KEY (`idNutricionistaFK`)
    REFERENCES `estacao_fitness`.`Nutricionista` (`idNutricionista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Dieta_Cliente1`
    FOREIGN KEY (`idAlunoFK`)
    REFERENCES `estacao_fitness`.`Aluno` (`idAluno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `estacao_fitness`.`tipoAlimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacao_fitness`.`tipoalimento` (
  `idtipoAlimento` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipoAlimento`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `estacao_fitness`.`Alimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacao_fitness`.`alimento` (
  `idAlimento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `urlImagem` VARCHAR(45) NOT NULL,
  `idTipoAlimentoFK` INT NOT NULL,
  PRIMARY KEY (`idAlimento`),
  INDEX `fk_Alimento_tipoAlimento1_idx` (`idTipoAlimentoFK` ASC),
  CONSTRAINT `fk_Alimento_tipoAlimento1`
    FOREIGN KEY (`idTipoAlimentoFK`)
    REFERENCES `estacao_fitness`.`tipoAlimento` (`idtipoAlimento`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacao_fitness`.`AlimentoDieta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacao_fitness`.`alimentodieta` (
  `idAlimentoDieta` INT NOT NULL AUTO_INCREMENT,
  `idDietaFK` INT NOT NULL,
  `idAlimentoFK` INT NOT NULL,
  INDEX `fk_Dieta_has_Alimento_Alimento1_idx` (`idAlimentoFK` ASC),
  INDEX `fk_Dieta_has_Alimento_Dieta1_idx` (`idDietaFK` ASC),
  PRIMARY KEY (`idAlimentoDieta`),
  CONSTRAINT `fk_Dieta_has_Alimento_Dieta1`
    FOREIGN KEY (`idDietaFK`)
    REFERENCES `estacao_fitness`.`Dieta` (`idDieta`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dieta_has_Alimento_Alimento1`
    FOREIGN KEY (`idAlimentoFK`)
    REFERENCES `estacao_fitness`.`Alimento` (`idAlimento`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacao_fitness`.`Lembrete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacao_fitness`.`lembrete` (
  `idLembrete` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `corpo` VARCHAR(45) NOT NULL,
  `idRecepcionistaFK` INT NOT NULL,
  PRIMARY KEY (`idLembrete`),
  INDEX `fk_Lembrete_Recepcionista1_idx` (`idRecepcionistaFK` ASC),
  CONSTRAINT `fk_Lembrete_Recepcionista1`
    FOREIGN KEY (`idRecepcionistaFK`)
    REFERENCES `estacao_fitness`.`Recepcionista` (`idRecepcionista`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacao_fitness`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacao_fitness`.`tipo` (
  `idTipo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `urlImagem` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacao_fitness`.`ExercicioTipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacao_fitness`.`exerciciotipo` (
  `idExercicioTipo` INT NOT NULL AUTO_INCREMENT,
  `Exercicio_idExercicio` INT NOT NULL,
  `Tipo_idTipo` INT NOT NULL,
  INDEX `fk_Exercicio_has_Tipo_Tipo1_idx` (`Tipo_idTipo` ASC),
  INDEX `fk_Exercicio_has_Tipo_Exercicio1_idx` (`Exercicio_idExercicio` ASC),
  PRIMARY KEY (`idExercicioTipo`),
  CONSTRAINT `fk_Exercicio_has_Tipo_Exercicio1`
    FOREIGN KEY (`Exercicio_idExercicio`)
    REFERENCES `estacao_fitness`.`Exercicio` (`idExercicio`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exercicio_has_Tipo_Tipo1`
    FOREIGN KEY (`Tipo_idTipo`)
    REFERENCES `estacao_fitness`.`Tipo` (`idTipo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `estacao_fitness`.`recepcionista` (`matricula`, `nome`, `cpf`, `endereco`, `status`, `senha`) VALUES ('123', 'teste', '1231232', 'teste', 'Ativo', '123');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
